services:
  # image name
  mongodb:
    image: mongo
    # ports
    ports:
      - 27017:27017
    # environments
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

  login:
    image: 'redis:6.2.8-alpine'
    command: redis-server --requirepass password
    ports:
      - '6666:6379'

  session-cache:
    image: 'redis:6.2.8-alpine'
    # command: redis-server --requirepass password
    ports:
      - '9999:6379'

  room-cache:
    image: 'redis:6.2.8-alpine'
    # command: redis-server --requirepass password
    ports:
      - '7777:6379'

  user-cache:
    image: 'redis:6.2.8-alpine'
    # command: redis-server --requirepass password
    ports:
      - '8888:6379'