services:
  chat_server:
    build: ./
    image: "chat_server:latest"
    container_name: chat_server
    command: sh -c "/home/chat_server/start-script"
    ports:
      - 28000:21583
    environment: 
      - "PORT=21583"
      - "LOGIN_URL=http://host.docker.internal:26000"
      - "MAN_URL=http://host.docker.internal:27000"
      - "PROD_SERVER=http://host.docker.internal:28000"