services:
 # image name
  mongodb:
    image: mongo
    # ports
    ports:
      - 27017
    # environments
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

  redis_cache:
    image: 'redis:6.2.8-alpine'
    command: redis-server --requirepass password
    ports:
      - 6379

  login_api:
    build: ./
    image: "login_api:latest"
    container_name: login_api
    command: sh -c "/home/loginAPI/wait && /home/loginAPI/start-script"
    ports:
      - 26000:21583
    environment:
      WAIT_HOSTS: mongo_express:8081, mongodb:27017, redis_cache:6379
